name: Test

on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Extract tags done
        run: git tag > tag-done
      - name: Extract releases exisiting
        run: curl https://pypi.org/pypi/awscli/json | jq -r '.releases | keys[]' > aws-tags
      - name: Get first unreleased tag
        run: grep -m 1 -Fxvf tag-done aws-tags | tr -d '\n' > latest
      - name: Commit latest
        run: |
          git config --local user.email "hannut91@gmail.com"
          git config --local user.name "Yunseok"
          git add latest
          git commit -m "update latest tag"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag
        uses: jaliborc/action-general-autotag@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source_file: latest
          extraction_regex: "(\\d+\\.\\d+\\.\\d+)"
          tag_message: "Automatic tag following AWS available release"
